### ISSUE TITLE
Select with Query

### ISSUE THREAD

**Issue by chrhuff** [fabianschenk86/firby-app#1]
Hi,

Blueprints using `type: select` and `options: query`, such as:

```
  galerie:
    label: Galerie
    width: 1/2
    type: select
    options: query
    query:
      fetch: pages
      page: galerie
      template: gallery
      text: '{{template}}: {{title}}'
      value: '{{uri}}'
```

Don't work in the firby-app:

![firby-select-query](https://cloud.githubusercontent.com/assets/3840590/16540313/a4bb90e0-4060-11e6-889d-ff1e32bf18ab.png)

**Comment by fabianschenk86** [comment]
<p>Thank you for your hint. Now, I have added the dynamic option in the <a href="https://github.com/fabianschenk86/firby-app/blob/master/firby.php"> firby.php</a> file.</p>

**Comment by chrhuff** [comment]
Installed the update, now pages with selects throw an error in the app.

**Comment by fabianschenk86** [comment]
Weird, it works for me. Then please try the following: Open your website and call the API like this  "www.**yourwebsite.de**?firby-username=**yourusername**&firby-password=**yourpasswort**&firby-type=currentpage&firby-uri=**siteuriwithselect**"  If an error message is displayed please send me the error message or a screenshot to fabianschenk86@googlemail.com

**Comment by chrhuff** [comment]
I get (actual paths sanitized)

```
Notice: Undefined index: tinyurl.enabled in /home/www/kirby/core/page.php on line 197
(repeated quite a few times)
Warning: Cannot modify header information - headers already sent by (output started at /home/www/kirby/core/page.php:197) in /home/www/kirby/toolkit/lib/cookie.php on line 164
```

followed by the JSON output.

[Update] I solved this myself by turning off debug mode.

Regular query selects look fine. However, I do actually have one of those in a structure, like this:

```
  calendars:
    label: Spiele und Ereignisse
    type: structure
    modalsize: medium
    entry: >
      {{url}} 
    fields:
      show:
        label: Zeige...
        type: checkboxes
        options:
          matches: Im Ergebnisdienst
          events: Auf dem Kalender
      url:
        label: Kalender
        type: select
        options: query
        width: 1
        query:
          fetch: pages
          template: calendar
          text: '{{title}} ({{uri}})'
          value: '{{uri}}'
        help: Referenz auf einen Kalender
```

That still renders as q u e r y like above.
